# Generated by Django 3.2.4 on 2022-02-22 12:12
from com.core.notes import models
from com.core.notes import views
from com.core.notes import serializers

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion




class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, max_length=30, null=True)),
                ('favourite_animal', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=120, null=True)),
                ('content_type', models.CharField(blank=True, choices=[('message', 'Message'), ('reminder', 'Reminder'), ('action', 'Action')], max_length=30, null=True)),
                ('created', models.DateTimeField(blank=True, max_length=30, null=True)),
                ('edited', models.DateTimeField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], max_length=30, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.userprofile')),
            ],
        ),
    ]
