name: CI/CD
on:
  push:
    branches:
      - 'dev'
      - 'stage'
      - 'master'
      - 'feature/**'
      - 'refactoring/**'
      - 'bugfix/**'
      - 'chore/**'
    pull_request:
      - 'dev'
      - 'master'
      - 'stage'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        db: [mysql]
        include:
          - db: mysql
            db_port: 3306

    services:
      # postgres db
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: r00t
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r com/requirements.txt
    - name: Install coverage
      run:
        pip install coverage

    - name: Run Tests
      env:
        DB: ${{ matrix.db }}
        DB_HOST: 127.0.0.1
        DB_PORT: ${{ matrix.db_port }}
        DB_PASSWORD: r00t
      run: |
        cd com
        coverage run manage.py test
        coverage report
        coverage xml
    
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml,
        flags: unittests
        fail_ci_if_error: true
