name: Hadrhat Testnet
on:
  push:
    branches:
      - 'dev'
      - 'stage'
      - 'master'
      - 'feature/**'
      - 'refactoring/**'
      - 'bugfix/**'
      - 'chore/**'
    pull_request:
      - 'dev'
      - 'master'
      - 'stage'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
    - name: Set up Python
      uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install node modules
      run: |
        npm install --save-dev "hardhat@^2.9.2" |
        "@nomiclabs/hardhat-waffle@^2.0.0" "ethereum-waffle@^3.0.0" |
        "chai@^4.2.0" "@nomiclabs/hardhat-ethers@^2.0.0" "ethers@^5.0.0"
    - name: Run hardhat test
      run: |
        cd hardhat
        npx hardhat test