name: CI/CD

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’
    - name: Echo something
      run:
        echo "There's a thing in my code!"
    - name: Run hardhat
      run:
        cd hardhat