name: Hadrhat Testnet
on:
  push:
    branches:
      - 'dev'
      - 'stage'
      - 'master'
      - 'feature/**'
      - 'refactoring/**'
      - 'bugfix/**'
      - 'chore/**'
    pull_request:
      - 'dev'
      - 'master'
      - 'stage'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
    - name: Set up Python
      uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Run npm test
      run: |
        npm test