name: Hadrhat Testnet
on:
  push:
    branches:
      - 'dev'
      - 'stage'
      - 'master'
      - 'feature/**'
      - 'refactoring/**'
      - 'bugfix/**'
      - 'chore/**'
    pull_request:
      - 'dev'
      - 'master'
      - 'stage'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
    - name: Set up Python
      uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Install node modules
      run: |
        cd hardhat
        npm i --save
    - name: Test smart contracts
      run: |
        cd hardhat
        npx hardhat test
    - name: Run hardhat node
      run: |
        cd hardhat
        npx hardhat node
        exit 1