name: Hadrhat Testnet
on:
  push:
    branches:
      - 'dev'
      - 'stage'
      - 'master'
      - 'feature/**'
      - 'refactoring/**'
      - 'bugfix/**'
      - 'chore/**'
    pull_request:
      - 'dev'
      - 'master'
      - 'stage'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
    - name: Set up Python
      uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    #- name: Install node modules
    #  run: |
    #   npm i --save
    #    npm install --save-dev hardhat
    - name: Install hardhat
      uses: NomicFoundation/hardhat@latest
      run: |
        cd hardhat
        npx hardhat test